title: "Iceland: land of fire and ice"
author: Anna H
email: anyagerasymchuk@gmail.com
description: Iceland is a different version of Paradise.
  
 # social links
instagram_username: anya.gerasymchuk
github_username:  annaherasymchuk

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
