title: "Iceland: land of fire and ice"
author: Anna H
email: anyagerasymchuk@gmail.com
description: Iceland is a different version of Paradise.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

social links
instagram_username: anya.gerasymchuk
github_username:  annaherasymchuk

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
